const config=window.MYTT;let singlesPlayers=[];let doublesTeams=[];
const TIERS=[{min:-Infinity,name:"Novice",icon:"🌿",cls:"tier-novice",next:1500},{min:1500,name:"Rookie",icon:"🌱",cls:"tier-rookie",next:1600},{min:1600,name:"Challenger",icon:"⚔️",cls:"tier-challenger",next:1700},{min:1700,name:"Elite",icon:"⭐",cls:"tier-elite",next:1800},{min:1800,name:"Master",icon:"🔥",cls:"tier-master",next:1900},{min:1900,name:"Legend",icon:"👑",cls:"tier-legend",next:2000},{min:2000,name:"Grandmaster",icon:"💎",cls:"tier-grandmaster",next:2100},{min:2100,name:"Immortal",icon:"⚡",cls:"tier-immortal",next:2200},{min:2200,name:"MYTT Champion",icon:"🏆",cls:"tier-champion",next:null}];
function getTier(r){const rating=Number(r)||0;let t=TIERS[0];for(const tier of TIERS){if(rating>=tier.min)t=tier}return t}
function tierHTML(r){const t=getTier(r);return `<span class="tier-pill ${t.cls}">${t.icon} ${t.name}</span>`}
function progressHTML(r){const rating=Number(r)||0;const t=getTier(r);if(!t.next)return `<div class="tier-progress"><div class="tier-progress-top"><span>${t.icon} ${t.name}</span><span>Top Tier</span></div><div class="progress-track"><div class="progress-fill" style="width:100%"></div></div><div class="progress-note">You have reached MYTT Champion tier.</div></div>`;const base=t.min===-Infinity?1400:t.min;const pct=Math.max(0,Math.min(100,((rating-base)/(t.next-base))*100));const next=TIERS.find(x=>x.min===t.next);return `<div class="tier-progress"><div class="tier-progress-top"><span>${t.icon} ${t.name}</span><span>${next.icon} ${next.name}</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="progress-note">${rating} / ${t.next} · ${t.next-rating} pts to ${next.name}</div></div>`}
function parseCSV(t){const r=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c=='"'&&q&&n=='"'){cell+='"';i++}else if(c=='"'){q=!q}else if(c==","&&!q){row.push(cell.trim());cell=""}else if((c=="\n"||c=="\r")&&!q){if(cell||row.length){row.push(cell.trim());r.push(row);row=[];cell=""}if(c=="\r"&&n=="\n")i++}else cell+=c}if(cell||row.length){row.push(cell.trim());r.push(row)}return r}
function cleanRows(rows){return rows.filter(row=>row.some(cell=>String(cell).trim()!="")).slice(1)}
function rowToItem(row,type){return{type,rank:row[0]||"-",name:row[1]||"-",rating:row[2]||"-",record:row[3]||"-",winRate:row[4]||"-",peak:row[5]||"-"}}
function rankLabel(rank){const v=String(rank||"").trim();if(v=="1")return"🥇 1";if(v=="2")return"🥈 2";if(v=="3")return"🥉 3";return v||"-"}
function makeRow(item){const tr=document.createElement("tr");tr.className="rank-"+String(item.rank||"").trim();tr.innerHTML=`<td><span class="rank-badge">${rankLabel(item.rank)}</span></td><td class="name" data-profile="${encodeURIComponent(item.name)}" data-type="${item.type}">${item.name}</td><td>${tierHTML(item.rating)}</td><td class="rating">${item.rating}</td><td>${item.record}</td><td>${item.winRate}</td><td>${item.peak}</td>`;return tr}
async function fetchRows(csvUrl){const url=csvUrl+(csvUrl.includes("?")?"&":"?")+"t="+Date.now();const res=await fetch(url);if(!res.ok)throw new Error("Unable to load CSV");return cleanRows(parseCSV(await res.text()))}
async function loadLeaderboard(csvUrl,bodyId,statusId,type,label){const body=document.getElementById(bodyId),status=document.getElementById(statusId);try{const rows=await fetchRows(csvUrl);const items=rows.map(row=>rowToItem(row,type));if(type=="singles")singlesPlayers=items;if(type=="doubles")doublesTeams=items;body.innerHTML="";if(!items.length){body.innerHTML=`<tr><td colspan="7" class="loading">No data yet.</td></tr>`;status.textContent="No data";return}items.forEach(item=>body.appendChild(makeRow(item)));status.textContent="Updated "+new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});updateSearchResults()}catch(e){console.error(e);body.innerHTML=`<tr><td colspan="7" class="loading">Failed to load ${label} leaderboard.</td></tr>`;status.textContent="Load failed"}}
function getAllSearchItems(){return[...singlesPlayers.map(i=>({...i,label:"Singles Player"})),...doublesTeams.map(i=>({...i,label:"Doubles Team"}))]}
function updateSearchResults(){const input=document.getElementById("playerSearch"),results=document.getElementById("searchResults");if(!input||!results)return;const q=input.value.trim().toLowerCase();if(!q){results.innerHTML=`<p class="muted">Type a player name to view rank, tier, rating, record, win rate and peak.</p>`;return}const matches=getAllSearchItems().filter(i=>i.name.toLowerCase().includes(q)).slice(0,8);if(!matches.length){results.innerHTML=`<p class="muted">No player or team found.</p>`;return}results.innerHTML=matches.map(i=>`<div class="search-result" data-profile="${encodeURIComponent(i.name)}" data-type="${i.type}"><div class="search-rank">${rankLabel(i.rank)}</div><div><div class="search-name">${i.name}</div><div class="search-meta">${i.label} · ${tierHTML(i.rating)} · W-L ${i.record} · Peak ${i.peak}</div></div><div class="search-rating">${i.rating}</div></div>`).join("")}
function findItem(type,name){const decoded=decodeURIComponent(name);const list=type=="doubles"?doublesTeams:singlesPlayers;return list.find(i=>i.name===decoded)}
function openProfile(type,name){const item=findItem(type,name);if(!item)return;document.getElementById("profileContent").innerHTML=`<div class="profile-top"><div class="profile-avatar">${type=="doubles"?"👥":"👤"}</div><div><h3>${item.name}</h3><p>${type=="doubles"?"Doubles Team":"Singles Player"} · Rank #${item.rank}</p>${tierHTML(item.rating)}</div></div><div class="profile-stats"><div class="stat"><small>Current Rating</small><strong>${item.rating}</strong></div><div class="stat"><small>Peak</small><strong>${item.peak}</strong></div><div class="stat"><small>Record</small><strong>${item.record}</strong></div><div class="stat"><small>Win Rate</small><strong>${item.winRate}</strong></div></div>${progressHTML(item.rating)}`;document.getElementById("profileModal").classList.remove("hidden")}
function closeProfile(){document.getElementById("profileModal").classList.add("hidden")}
function bindEvents(){const input=document.getElementById("playerSearch");if(input)input.addEventListener("input",updateSearchResults);document.addEventListener("click",e=>{const p=e.target.closest("[data-profile]");if(p)openProfile(p.dataset.type,p.dataset.profile);if(e.target.matches("[data-close-modal]"))closeProfile()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeProfile()})}
function loadAll(){loadLeaderboard(config.singlesCsv,"singlesBody","singlesStatus","singles","singles");loadLeaderboard(config.doublesCsv,"doublesBody","doublesStatus","doubles","doubles")}
bindEvents();loadAll();setInterval(loadAll,60000);